baseurl: '/'
permalink: pretty
title: 'Papelo'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/papelo.png" # "images/logo/logo-mobile.svg"
  desktop: "images/logo/Papelo-Baloo-Thambi.jpg" # "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'Built on Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Papelo"
  meta_og_type: "website"
  meta_og_url: "https://papelo.co"
  meta_og_image: "https://papelo.co/images/logo/Papelo-Baloo-Thambi.jpg"
  meta_og_description: "Papelo is a simple, sophisticated, all-in-one solution to easily manage the creation, editing, and collection of digital and paper forms."
  meta_twitter_card: "summary"
  meta_twitter_site: "@"
  meta_twitter_creator: "@"

collections:
  products:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md